package svm;

/**
 * Class that simulates a Stack Virtual Machine (SVM) by executing MIPS machine code (no labels and no assembly mnemonic
 * instructions, just numbers) on a virtual MIPS processor. The machine code is generated with ANTLR according to the
 * MIPS ISA from the MIPS assembly generated by the Compiler.
 */
public class ExecuteVM {
    public static final int CODESIZE = 10_000;
    public static final int MEMSIZE = 10_000;

    // Memory layout
    private final int[] code;
    private final int[] memory = new int[MEMSIZE]; // stack + heap (MEMSIZE-0)

    // Registers
    private int ip = 0; // instruction pointer
    private int sp = MEMSIZE; // stack pointer
    private int hp = 0; // heap pointer
    private int fp = MEMSIZE; // frame pointer
    private int ra; // return address
    private int tm; // temporary storage

    public ExecuteVM(int[] code) {
        this.code = code;
    }

    public void cpu() {
        while (true) {
            int bytecode = code[ip++]; // fetch
            int v1, v2;
            int address;
            switch (bytecode) { // decode + execute
                case SVMParser.PUSH:
                    push(code[ip++]);
                    break;
                case SVMParser.POP:
                    pop();
                    break;
                case SVMParser.ADD:
                    v1 = pop();
                    v2 = pop();
                    push(v2 + v1);
                    break;
                case SVMParser.MULT:
                    v1 = pop();
                    v2 = pop();
                    push(v2 * v1);
                    break;
                case SVMParser.DIV:
                    v1 = pop();
                    v2 = pop();
                    push(v2 / v1);
                    break;
                case SVMParser.SUB:
                    v1 = pop();
                    v2 = pop();
                    push(v2 - v1);
                    break;
                case SVMParser.STOREW:
                    address = pop();
                    memory[address] = pop();
                    break;
                case SVMParser.LOADW:
                    push(memory[pop()]);
                    break;
                case SVMParser.BRANCH:
                    address = code[ip];
                    ip = address;
                    break;
                case SVMParser.BRANCHEQ:
                    address = code[ip++];
                    v1 = pop();
                    v2 = pop();
                    if (v2 == v1) ip = address;
                    break;
                case SVMParser.BRANCHLESSEQ:
                    address = code[ip++];
                    v1 = pop();
                    v2 = pop();
                    if (v2 <= v1) ip = address;
                    break;
                case SVMParser.JS:
                    address = pop();
                    ra = ip;
                    ip = address;
                    break;
                case SVMParser.STORERA:
                    ra = pop();
                    break;
                case SVMParser.LOADRA:
                    push(ra);
                    break;
                case SVMParser.STORETM:
                    tm = pop();
                    break;
                case SVMParser.LOADTM:
                    push(tm);
                    break;
                case SVMParser.STOREFP:
                    fp = pop();
                    break;
                case SVMParser.LOADFP:
                    push(fp);
                    break;
                case SVMParser.COPYFP:
                    fp = sp;
                    break;
                case SVMParser.STOREHP:
                    hp = pop();
                    break;
                case SVMParser.LOADHP:
                    push(hp);
                    break;
                case SVMParser.PRINT:
                    System.out.println((sp < MEMSIZE) ? memory[sp] : "Empty stack!");
                    break;
                case SVMParser.HALT:
                    return;
            }
        }
    }

    private int pop() {
        return memory[sp++];
    }

    private void push(int v) {
        memory[--sp] = v;
    }
}
