package compiler;

import static compiler.lib.FOOLlib.extractCtxName;
import static compiler.lib.FOOLlib.lowerizeFirstChar;

import compiler.AST.*;
import compiler.FOOLParser.*;
import compiler.lib.DecNode;
import compiler.lib.Node;
import compiler.lib.TypeNode;
import java.util.ArrayList;
import java.util.List;
import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ParseTree;

/**
 * Class that represents a visitor of a Syntax Tree to transform it into an Abstract Syntax Tree (ST -> AST).
 *
 * <p>Performs the last step of the Parser (2-nd component of the Compiler).
 *
 * <p>Starts from a stream of tokens generated by the Lexer (1-st component of the Compiler).
 */
public class ASTGenerationSTVisitor extends FOOLBaseVisitor<Node> {
    public boolean print;
    String indent;

    public ASTGenerationSTVisitor() {}

    public ASTGenerationSTVisitor(boolean debug) {
        print = debug;
    }

    private void printVarAndProdName(ParserRuleContext ctx) {
        String prefix = "";
        Class<?> ctxClass = ctx.getClass(), parentClass = ctxClass.getSuperclass();
        // parentClass is the var context (and not ctxClass itself)
        if (!parentClass.equals(ParserRuleContext.class)) {
            prefix = lowerizeFirstChar(extractCtxName(parentClass.getName())) + ": production #";
        }
        System.out.println(indent + prefix + lowerizeFirstChar(extractCtxName(ctxClass.getName())));
    }

    @Override
    public Node visit(ParseTree t) {
        if (t == null) return null;
        String temp = indent;
        indent = (indent == null) ? "" : indent + "  ";
        Node result = super.visit(t);
        indent = temp;
        return result;
    }

    @Override
    public Node visitProg(ProgContext c) {
        if (print) printVarAndProdName(c);
        return visit(c.progbody());
    }

    @Override
    public Node visitLetInProg(LetInProgContext c) {
        if (print) printVarAndProdName(c);
        List<DecNode> declist = new ArrayList<>();
        for (CldecContext cldec : c.cldec()) declist.add((DecNode) visit(cldec));
        for (DecContext dec : c.dec()) declist.add((DecNode) visit(dec));
        return new ProgLetInNode(declist, visit(c.exp()));
    }

    @Override
    public Node visitNoDecProg(NoDecProgContext c) {
        if (print) printVarAndProdName(c);
        return new ProgNode(visit(c.exp()));
    }

    @Override
    public Node visitTimesDiv(TimesDivContext c) {
        if (print) printVarAndProdName(c);
        Node n;
        if (c.TIMES() != null) {
            n = new TimesNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.TIMES().getSymbol().getLine());
        } else if (c.DIV() != null) {
            n = new DivNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.DIV().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    @Override
    public Node visitPlusMinus(PlusMinusContext c) {
        if (print) printVarAndProdName(c);
        Node n;
        if (c.PLUS() != null) {
            n = new PlusNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.PLUS().getSymbol().getLine());
        } else if (c.MINUS() != null) {
            n = new MinusNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.MINUS().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    @Override
    public Node visitComp(CompContext c) {
        if (print) printVarAndProdName(c);
        Node n;
        if (c.EQ() != null) {
            n = new EqualNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.EQ().getSymbol().getLine());
        } else if (c.GE() != null) {
            n = new GreaterEqualNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.GE().getSymbol().getLine());
        } else if (c.LE() != null) {
            n = new LessEqualNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.LE().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    @Override
    public Node visitAndOr(AndOrContext c) {
        if (print) printVarAndProdName(c);
        Node n;
        if (c.AND() != null) {
            n = new AndNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.AND().getSymbol().getLine());
        } else if (c.OR() != null) {
            n = new OrNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.OR().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    public Node visitNot(NotContext c) {
        if (print) printVarAndProdName(c);
        Node n = new NotNode(visit(c.exp()));
        n.setLine(c.NOT().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitVardec(VardecContext c) {
        if (print) printVarAndProdName(c);
        Node n = null;
        if (c.ID() != null) { // non-incomplete ST
            n = new VarNode(c.ID().getText(), (TypeNode) visit(c.type()), visit(c.exp()));
            n.setLine(c.VAR().getSymbol().getLine());
        }
        return n;
    }

    @Override
    public Node visitFundec(FundecContext c) {
        if (print) printVarAndProdName(c);
        List<ParNode> parList = new ArrayList<>();
        for (int i = 1; i < c.ID().size(); i++) {
            ParNode p = new ParNode(c.ID(i).getText(), (TypeNode) visit(c.type(i)));
            p.setLine(c.ID(i).getSymbol().getLine());
            parList.add(p);
        }
        List<DecNode> decList = new ArrayList<>();
        for (DecContext dec : c.dec()) decList.add((DecNode) visit(dec));
        Node n = null;
        if (!c.ID().isEmpty()) { // non-incomplete ST
            n = new FunNode(c.ID(0).getText(), (TypeNode) visit(c.type(0)), parList, decList, visit(c.exp()));
            n.setLine(c.FUN().getSymbol().getLine());
        }
        return n;
    }

    // TODO: In every OOP context where the token ID is not the first token of the production,
    //  it's necessary to check whether the ID exists. This is true for the following productions:
    //  - cldec: Check that the list of IDs is not empty (!c.ID().isEmpty())
    //  - methdec: same as cldec
    //  - new: Check that ID is not null (c.ID() != null)
    //  - dotcall: Check that the second ID is not null (?)

    @Override
    public Node visitIntType(IntTypeContext c) {
        if (print) printVarAndProdName(c);
        return new IntTypeNode();
    }

    @Override
    public Node visitBoolType(BoolTypeContext c) {
        if (print) printVarAndProdName(c);
        return new BoolTypeNode();
    }

    @Override
    public Node visitInteger(IntegerContext c) {
        if (print) printVarAndProdName(c);
        int v = Integer.parseInt(c.NUM().getText());
        return new IntNode(c.MINUS() == null ? v : -v);
    }

    @Override
    public Node visitTrue(TrueContext c) {
        if (print) printVarAndProdName(c);
        return new BoolNode(true);
    }

    @Override
    public Node visitFalse(FalseContext c) {
        if (print) printVarAndProdName(c);
        return new BoolNode(false);
    }

    @Override
    public Node visitIf(IfContext c) {
        if (print) printVarAndProdName(c);
        Node ifNode = visit(c.exp(0));
        Node thenNode = visit(c.exp(1));
        Node elseNode = visit(c.exp(2));
        Node n = new IfNode(ifNode, thenNode, elseNode);
        n.setLine(c.IF().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitPrint(PrintContext c) {
        if (print) printVarAndProdName(c);
        return new PrintNode(visit(c.exp()));
    }

    @Override
    public Node visitPars(ParsContext c) {
        if (print) printVarAndProdName(c);
        return visit(c.exp());
    }

    @Override
    public Node visitId(IdContext c) {
        if (print) printVarAndProdName(c);
        Node n = new IdNode(c.ID().getText());
        n.setLine(c.ID().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitCall(CallContext c) {
        if (print) printVarAndProdName(c);
        List<Node> arglist = new ArrayList<>();
        for (ExpContext arg : c.exp()) arglist.add(visit(arg));
        Node n = new CallNode(c.ID().getText(), arglist);
        n.setLine(c.ID().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitCldec(CldecContext c) {
        if (print) printVarAndProdName(c);
        List<FieldNode> fieldsList = new ArrayList<>();
        List<MethodNode> methodsList = new ArrayList<>();
        for (int i = 1; i < c.ID().size(); i++) {
            FieldNode f = new FieldNode(c.ID(i).getText(), (TypeNode) visit(c.type(i - 1)));
            f.setLine(c.ID(i).getSymbol().getLine());
            fieldsList.add(f);
        }
        for (MethdecContext methdec : c.methdec()) {
            methodsList.add((MethodNode) visit(methdec));
        }
        Node n = null;
        if (!c.ID().isEmpty()) {
            n = new ClassNode(c.ID(0).getText(), fieldsList, methodsList);
            n.setLine(c.CLASS().getSymbol().getLine());
        }
        return n;
    }

    @Override
    public Node visitMethdec(MethdecContext c) {
        if (print) printVarAndProdName(c);
        List<ParNode> parList = new ArrayList<>();
        for (int i = 1; i < c.ID().size(); i++) {
            ParNode p = new ParNode(c.ID(i).getText(), (TypeNode) visit(c.type(i)));
            p.setLine(c.ID(i).getSymbol().getLine());
            parList.add(p);
        }
        List<DecNode> decList = new ArrayList<>();
        for (DecContext dec : c.dec()) decList.add((DecNode) visit(dec));
        Node n = null;
        if (!c.ID().isEmpty()) { // non-incomplete ST
            n = new MethodNode(c.ID(0).getText(), (TypeNode) visit(c.type(0)), parList, decList, visit(c.exp()));
            n.setLine(c.FUN().getSymbol().getLine());
        }
        return n;
    }

    @Override
    public Node visitNew(NewContext c) {
        if (print) printVarAndProdName(c);
        List<Node> argsList = new ArrayList<>();
        for (ExpContext exp : c.exp()) {
            argsList.add(visit(exp));
        }
        Node n = null;
        if (c.ID() != null) {
            n = new NewNode(c.ID().getText(), argsList);
            n.setLine(c.NEW().getSymbol().getLine());
        }
        return n;
    }

    @Override
    public Node visitDotCall(DotCallContext c) {
        if (print) printVarAndProdName(c);
        List<Node> argsList = new ArrayList<>();
        for (ExpContext exp : c.exp()) {
            argsList.add(visit(exp));
        }
        Node n = null;
        if (c.ID(1) != null) {
            n = new ClassCallNode(c.ID(0).getText(), c.ID(1).getText(), argsList);
            n.setLine(c.ID(0).getSymbol().getLine());
        }
        return n;
    }

    @Override
    public Node visitNull(NullContext c) {
        if (print) printVarAndProdName(c);
        Node n = new EmptyNode();
        n.setLine(c.NULL().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitIdType(IdTypeContext c) {
        if (print) printVarAndProdName(c);
        return new RefTypeNode(c.ID().getText());
    }
}
