package compiler;

import static compiler.lib.FOOLlib.extractCtxName;
import static compiler.lib.FOOLlib.lowerizeFirstChar;

import compiler.AST.*;
import compiler.FOOLParser.*;
import compiler.lib.DecNode;
import compiler.lib.Node;
import compiler.lib.TypeNode;
import java.util.ArrayList;
import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ParseTree;

/**
 * Class that represents a visitor of a Syntax Tree to transform it into an Abstract Syntax Tree (ST -> AST).
 *
 * <p>Performs the last step of the Parser (2-nd component of the Compiler).
 *
 * <p>Starts from a stream of tokens generated by the Lexer (1-st component of the Compiler).
 */
public class ASTGenerationSTVisitor extends FOOLBaseVisitor<Node> {
    public boolean print;
    String indent;

    public ASTGenerationSTVisitor() { }

    public ASTGenerationSTVisitor(final boolean debug) {
        print = debug;
    }

    private void printVarAndProdName(final ParserRuleContext ctx) {
        var prefix = "";
        final Class<?> ctxClass = ctx.getClass();
        final Class<?> parentClass = ctxClass.getSuperclass();
        // parentClass is the var context (and not ctxClass itself)
        if (!parentClass.equals(ParserRuleContext.class)) {
            prefix = lowerizeFirstChar(extractCtxName(parentClass.getName())) + ": production #";
        }
        IO.println(indent + prefix + lowerizeFirstChar(extractCtxName(ctxClass.getName())));
    }

    @Override
    public Node visit(final ParseTree t) {
        if (t == null) {
            return null;
        }
        final String temp = indent;
        indent = indent == null ? "" : indent + "  ";
        final Node result = super.visit(t);
        indent = temp;
        return result;
    }

    @Override
    public Node visitProg(final ProgContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return visit(c.progbody());
    }

    @Override
    public Node visitLetInProg(final LetInProgContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var declist = new ArrayList<DecNode>();
        for (CldecContext cldec : c.cldec()) {
            declist.add((DecNode) visit(cldec));
        }
        for (DecContext dec : c.dec()) {
            declist.add((DecNode) visit(dec));
        }
        return new ProgLetInNode(declist, visit(c.exp()));
    }

    @Override
    public Node visitNoDecProg(final NoDecProgContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return new ProgNode(visit(c.exp()));
    }

    @Override
    public Node visitTimesDiv(final TimesDivContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        Node n;
        if (c.TIMES() != null) {
            n = new TimesNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.TIMES().getSymbol().getLine());
        } else if (c.DIV() != null) {
            n = new DivNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.DIV().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    @Override
    public Node visitPlusMinus(final PlusMinusContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        Node n;
        if (c.PLUS() != null) {
            n = new PlusNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.PLUS().getSymbol().getLine());
        } else if (c.MINUS() != null) {
            n = new MinusNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.MINUS().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    @Override
    public Node visitComp(final CompContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        Node n;
        if (c.EQ() != null) {
            n = new EqualNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.EQ().getSymbol().getLine());
        } else if (c.GE() != null) {
            n = new GreaterEqualNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.GE().getSymbol().getLine());
        } else if (c.LE() != null) {
            n = new LessEqualNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.LE().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    @Override
    public Node visitAndOr(final AndOrContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        Node n;
        if (c.AND() != null) {
            n = new AndNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.AND().getSymbol().getLine());
        } else if (c.OR() != null) {
            n = new OrNode(visit(c.exp(0)), visit(c.exp(1)));
            n.setLine(c.OR().getSymbol().getLine());
        } else {
            throw new IllegalStateException("Every type of operator is null.");
        }
        return n;
    }

    @Override
    public Node visitNot(final NotContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final Node n = new NotNode(visit(c.exp()));
        n.setLine(c.NOT().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitVardec(final VardecContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        // c.ID() could have an unexpected value here, errors must be checked before this phase
        final Node n = new VarNode(c.ID().getText(), (TypeNode) visit(c.type()), visit(c.exp()));
        n.setLine(c.VAR().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitFundec(final FundecContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var parList = new ArrayList<ParNode>();
        for (var i = 1; i < c.ID().size(); i++) {
            final var p = new ParNode(c.ID(i).getText(), (TypeNode) visit(c.type(i)));
            p.setLine(c.ID(i).getSymbol().getLine());
            parList.add(p);
        }
        final var decList = new ArrayList<DecNode>();
        for (DecContext dec : c.dec()) {
            decList.add((DecNode) visit(dec));
        }
        // c.ID(0) could have an unexpected value here, errors must be checked before this phase
        // c.ID().isEmpty() is ALWAYS FALSE
        final Node n = new FunNode(c.ID(0).getText(), (TypeNode) visit(c.type(0)), parList, decList, visit(c.exp()));
        n.setLine(c.FUN().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitIntType(final IntTypeContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return new IntTypeNode();
    }

    @Override
    public Node visitBoolType(final BoolTypeContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return new BoolTypeNode();
    }

    @Override
    public Node visitInteger(final IntegerContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var v = Integer.parseInt(c.NUM().getText());
        return new IntNode(c.MINUS() == null ? v : -v);
    }

    @Override
    public Node visitTrue(final TrueContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return new BoolNode(true);
    }

    @Override
    public Node visitFalse(final FalseContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return new BoolNode(false);
    }

    @Override
    public Node visitIf(final IfContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final Node ifNode = visit(c.exp(0));
        final Node thenNode = visit(c.exp(1));
        final Node elseNode = visit(c.exp(2));
        final Node n = new IfNode(ifNode, thenNode, elseNode);
        n.setLine(c.IF().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitPrint(final PrintContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return new PrintNode(visit(c.exp()));
    }

    @Override
    public Node visitPars(final ParsContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return visit(c.exp());
    }

    @Override
    public Node visitId(final IdContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final Node n = new IdNode(c.ID().getText());
        n.setLine(c.ID().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitCall(final CallContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var arglist = new ArrayList<Node>();
        for (ExpContext arg : c.exp()) {
            arglist.add(visit(arg));
        }
        final Node n = new CallNode(c.ID().getText(), arglist);
        n.setLine(c.ID().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitCldec(final CldecContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var fields = new ArrayList<FieldNode>();
        for (var i = 1; i < c.ID().size(); i++) {
            final var field = new FieldNode(c.ID(i).getText(), (TypeNode) visit(c.type(i - 1)));
            field.setLine(c.ID(i).getSymbol().getLine());
            fields.add(field);
        }
        final var methods = new ArrayList<MethodNode>();
        for (MethdecContext mdec : c.methdec()) {
            methods.add((MethodNode) visit(mdec));
        }
        // c.ID(0) could have an unexpected value here, errors must be checked before this phase
        // c.ID().isEmpty() is ALWAYS FALSE
        final Node n = new ClassNode(c.ID(0).getText(), fields, methods);
        n.setLine(c.CLASS().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitMethdec(final MethdecContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var pars = new ArrayList<ParNode>();
        for (var i = 1; i < c.ID().size(); i++) {
            final var par = new ParNode(c.ID(i).getText(), (TypeNode) visit(c.type(i)));
            par.setLine(c.ID(i).getSymbol().getLine());
            pars.add(par);
        }
        final var decs = new ArrayList<DecNode>();
        for (DecContext dec : c.dec()) {
            decs.add((DecNode) visit(dec));
        }
        // c.ID(0) could have an unexpected value here, errors must be checked before this phase
        // c.ID().isEmpty() is ALWAYS FALSE
        final Node n = new MethodNode(c.ID(0).getText(), (TypeNode) visit(c.type(0)), pars, decs, visit(c.exp()));
        n.setLine(c.FUN().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitNull(final NullContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final Node n = new EmptyNode();
        n.setLine(c.NULL().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitNew(final NewContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var args = new ArrayList<Node>();
        for (ExpContext arg : c.exp()) {
            args.add(visit(arg));
        }
        // c.ID() could have an unexpected value here, errors must be checked before this phase
        final Node n = new NewNode(c.ID().getText(), args);
        n.setLine(c.NEW().getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitDotCall(final DotCallContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        final var args = new ArrayList<Node>();
        for (ExpContext arg : c.exp()) {
            args.add(visit(arg));
        }
        // c.ID() could have an unexpected value here, errors must be checked before this phase
        final Node n = new ClassCallNode(c.ID(0).getText(), c.ID(1).getText(), args);
        n.setLine(c.ID(0).getSymbol().getLine());
        return n;
    }

    @Override
    public Node visitIdType(final IdTypeContext c) {
        if (print) {
            printVarAndProdName(c);
        }
        return new RefTypeNode(c.ID().getText());
    }
}
